### ISSUE TITLE
Segmentation Fault in IGC when generating the GPU binary.

### ISSUE THREAD

**Issue by chengjunlu** [intel/mlir-extensions#639] opened 2023-04-21 03:37 UTC
A segmentation fault issue happened when generating the GPU binary for Triton language.

Here is the call stack trace when the issue happened:
![image](https://user-images.githubusercontent.com/63445766/233535064-af3666df-b775-4689-a2ac-a680d75da6d3.png)

Here is the versions of driver I used:
```
ii  intel-fw-gpu                               2022.39.4+180                         all          Firmware package for Intel integrated and discrete GPUs
ii  intel-fw-gpu-prerelease                    2022.39.4+180                         all          Firmware package for Intel integrated and discrete GPUs
ii  intel-gsc                                  0.8.4+36                              amd64        Intel(R) Graphics System Controller Firmware
ii  intel-gsc-dev                              0.8.4+36                              amd64        Intel(R) Graphics System Controller Firmware
ii  intel-igc-cm                               1.0.170+i54~u20.04                    amd64        Intel(R) C for Metal Compiler -- CM Frontend lib
pi  intel-igc-core                             1.0.12504.5                           amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-igc-opencl                           1.0.12504.5                           amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-level-zero-gpu                       1.3.24595.30                          amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
ii  intel-level-zero-gpu-dbgsym                1.3.23681                             amd64        debug symbols for intel-level-zero-gpu
ii  intel-microcode                            3.20210608.0ubuntu0.20.04.1           amd64        Processor microcode firmware for Intel CPUs
ii  intel-opencl-icd                           22.43.24595.30                        amd64        Intel graphics compute runtime for OpenCL
ii  intel-opencl-icd-dbgsym                    22.27.23681                           amd64        debug symbols for intel-opencl-icd
```

The attached is the IGC dumped log.

[igc dump log.zip](https://github.com/intel/mlir-extensions/files/11292024/igc.dump.log.zip)

**Comment by chengjunlu** [comment] 2023-05-05 00:42
So far we can not reproduce this issue with 2023.1 oneAPI bundle. low priority this issue.

**Comment by drprajap** [comment] 2023-05-23 21:26
As the issue is not reproducible with latest oneAPI, closing the issue, please reopen if it is seen in future.

**Closed by drprajap** 2023-05-23 21:26 UTC
Labels: Triton
